from typing import Protocol, Sequence, Optional, Any
from uuid import UUID

from yukinoise_users.domain.models import User, Profile, UserSettings, UserAuditLog
from yukinoise_users.domain.value_objects import (
    UserStatus,
    UserAuditAction,
    UserChangedBy,
)


class UsersRepository(Protocol):
    async def create_from_keycloak(self, keycloak_id: UUID, email_verified: bool = False) -> User:
        ...

    async def get_by_id(self, user_id: UUID) -> Optional[User]:
        ...

    async def get_by_id_with_profile(self, user_id: UUID) -> Optional[User]:
        ...

    async def get_by_id_full(self, user_id: UUID) -> Optional[User]:
        ...

    async def get_by_ids(self, user_ids: list[UUID]) -> Sequence[User]:
        ...

    async def exists(self, user_id: UUID) -> bool:
        ...

    async def get_by_status(self, status: UserStatus, limit: int = 100, offset: int = 0) -> Sequence[User]:
        ...

    async def get_active_users(self, limit: int = 100, offset: int = 0) -> Sequence[User]:
        ...

    async def get_recently_active(self, since_timestamp: int, limit: int = 100) -> Sequence[User]:
        ...

    async def update_last_login(self, user_id: UUID, timestamp: int) -> None:
        ...

    async def update_email_verified(self, user_id: UUID, verified: bool) -> None:
        ...

    async def update_status(self, user_id: UUID, status: UserStatus) -> None:
        ...

    async def suspend_user(self, user_id: UUID) -> None:
        ...

    async def ban_user(self, user_id: UUID) -> None:
        ...

    async def activate_user(self, user_id: UUID) -> None:
        ...

    async def soft_delete(self, user_id: UUID, timestamp: int) -> None:
        ...

    async def restore(self, user_id: UUID) -> None:
        ...

    async def count_by_status(self, status: UserStatus) -> int:
        ...

    async def count_total_active(self) -> int:
        ...

    async def count_registered_since(self, since_timestamp: int) -> int:
        ...


class ProfilesRepository(Protocol):
    async def create(self, user_id: UUID, **profile_data: Any) -> Profile:
        ...

    async def get_by_user_id(self, user_id: UUID) -> Optional[Profile]:
        ...

    async def get_by_user_ids(self, user_ids: list[UUID]) -> Sequence[Profile]:
        ...

    async def get_by_display_name(self, display_name: str) -> Optional[Profile]:
        ...

    async def get_by_display_name_ilike(self, pattern: str, limit: int = 100) -> Sequence[Profile]:
        ...

    async def exists_display_name(self, display_name: str) -> bool:
        ...

    async def search_fulltext(self, query_text: str, limit: int = 100) -> Sequence[Profile]:
        ...

    async def get_by_genres(self, genres: list[str], limit: int = 100) -> Sequence[Profile]:
        ...

    async def get_by_tags(self, tags: list[str], limit: int = 100) -> Sequence[Profile]:
        ...

    async def get_verified(self, limit: int = 100, offset: int = 0) -> Sequence[Profile]:
        ...

    async def get_top_by_monthly_listeners(self, limit: int = 100, offset: int = 0) -> Sequence[Profile]:
        ...

    async def get_top_by_followers(self, limit: int = 100, offset: int = 0) -> Sequence[Profile]:
        ...

    async def update_profile(self, user_id: UUID, **updates: Any) -> None:
        ...

    async def update_avatar(self, user_id: UUID, avatar_url: str | None) -> None:
        ...

    async def update_banner(self, user_id: UUID, banner_url: str | None) -> None:
        ...

    async def increment_followers(self, user_id: UUID) -> None:
        ...

    async def decrement_followers(self, user_id: UUID) -> None:
        ...

    async def increment_following(self, user_id: UUID) -> None:
        ...

    async def decrement_following(self, user_id: UUID) -> None:
        ...

    async def increment_releases(self, user_id: UUID) -> None:
        ...

    async def decrement_releases(self, user_id: UUID) -> None:
        ...

    async def increment_featured_in_releases(self, user_id: UUID) -> None:
        ...

    async def decrement_featured_in_releases(self, user_id: UUID) -> None:
        ...

    async def set_verified(self, user_id: UUID, verified: bool) -> None:
        ...

    async def update_monthly_listeners(self, user_id: UUID, count: int) -> None:
        ...

    async def soft_delete(self, user_id: UUID, timestamp: int) -> None:
        ...

    async def restore(self, user_id: UUID) -> None:
        ...


class UserSettingsRepository(Protocol):
    async def get(self, user_id: UUID) -> Optional[UserSettings]:
        ...

    async def update(self, user_id: UUID, **updates: Any) -> None:
        ...

    async def create(self, user_id: UUID, **settings: Any) -> UserSettings:
        ...

    async def soft_delete(self, user_id: UUID, timestamp: int) -> None:
        ...

    async def restore(self, user_id: UUID) -> None:
        ...


class UserAuditLogsRepository(Protocol):
    async def create(self, user_id: UUID, action: UserAuditAction, changed_by: UserChangedBy, details: dict | None = None) -> UserAuditLog:
        ...

    async def list_for_user(self, user_id: UUID, limit: int = 100) -> Sequence[UserAuditLog]:
        ...
