from typing import Protocol, BinaryIO


class S3StorageClient(Protocol):
    async def get_file_url(self, bucket: str, file_key: str) -> str: ...

    async def upload_file(
        self, file_key: str, bucket: str, stream: BinaryIO, part_size: int
    ) -> None: ...

    async def delete_file(self, bucket: str, file_key: str) -> None: ...

    async def delete_batch_files(self, bucket: str, file_keys: list[str]) -> None: ...

    async def move_file(self, bucket: str, source_key: str, dest_key: str) -> None: ...

    async def is_file(self, bucket: str, file_key: str) -> bool: ...

    async def list_files(self, bucket: str, prefix: str) -> list[str]: ...

    async def close(self) -> None: ...

    def generate_key(self, prefix: str, filename: str) -> str: ...
