"""Initial

Revision ID: f772e5b2afc9
Revises: 
Create Date: 2026-01-03 19:26:04.974571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f772e5b2afc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure 'users' schema exists before creating tables
    op.execute("CREATE SCHEMA IF NOT EXISTS users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('updated_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('last_login_at', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index('idx_users_last_login_at', 'users', ['last_login_at'], unique=False, schema='users')
    op.create_index('idx_users_status', 'users', ['status'], unique=False, schema='users')
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('releases_count', sa.Integer(), nullable=False),
    sa.Column('featured_in_releases_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('updated_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_index('idx_profiles_display_name', 'profiles', ['display_name'], unique=True, schema='users')
    op.create_index('idx_profiles_preferred_genres', 'profiles', ['preferred_genres'], unique=False, schema='users', postgresql_using='gin')
    op.create_index('idx_profiles_search_vector', 'profiles', ['search_vector'], unique=False, schema='users', postgresql_using='gin')
    op.create_index('idx_profiles_social_links', 'profiles', ['social_links'], unique=False, schema='users', postgresql_using='gin')
    op.create_index('idx_profiles_tags', 'profiles', ['tags'], unique=False, schema='users', postgresql_using='gin')
    op.create_table('user_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'PROFILE_UPDATE', 'ACCOUNT_DELETION', name='userauditaction'), nullable=False),
    sa.Column('changed_by', sa.Enum('USER', 'ADMIN', 'SYSTEM', name='userchangedby'), nullable=False),
    sa.Column('timestamp', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index('idx_user_audit_logs_action', 'user_audit_logs', ['action'], unique=False, schema='users')
    op.create_index('idx_user_audit_logs_user_id', 'user_audit_logs', ['user_id'], unique=False, schema='users')
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('playback_quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'LOSSLESS', name='userplaybackquality'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoplay_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_consent', sa.Boolean(), nullable=False),
    sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.Integer(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings', schema='users')
    op.drop_index('idx_user_audit_logs_user_id', table_name='user_audit_logs', schema='users')
    op.drop_index('idx_user_audit_logs_action', table_name='user_audit_logs', schema='users')
    op.drop_table('user_audit_logs', schema='users')
    op.drop_index('idx_profiles_tags', table_name='profiles', schema='users', postgresql_using='gin')
    op.drop_index('idx_profiles_social_links', table_name='profiles', schema='users', postgresql_using='gin')
    op.drop_index('idx_profiles_search_vector', table_name='profiles', schema='users', postgresql_using='gin')
    op.drop_index('idx_profiles_preferred_genres', table_name='profiles', schema='users', postgresql_using='gin')
    op.drop_index('idx_profiles_display_name', table_name='profiles', schema='users')
    op.drop_table('profiles', schema='users')
    op.drop_index('idx_users_status', table_name='users', schema='users')
    op.drop_index('idx_users_last_login_at', table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
